package co.edu.campusucc.sd.modelo;
// Generated 28/03/2020 03:58:47 PM by Hibernate Tools 5.4.7.Final

import java.math.BigInteger;

/**
 * Biometria generated by hbm2java
 */
public class Biometria implements java.io.Serializable {

	private BigInteger idBiometria;
	private Cliente cliente;
	private byte[] huellaDigital1;
	private byte[] huellaDigital2;

	public Biometria() {
	}

	public Biometria(BigInteger idBiometria, byte[] huellaDigital1, byte[] huellaDigital2) {
		this.idBiometria = idBiometria;
		this.huellaDigital1 = huellaDigital1;
		this.huellaDigital2 = huellaDigital2;
	}

	public Biometria(BigInteger idBiometria, Cliente cliente, byte[] huellaDigital1, byte[] huellaDigital2) {
		this.idBiometria = idBiometria;
		this.cliente = cliente;
		this.huellaDigital1 = huellaDigital1;
		this.huellaDigital2 = huellaDigital2;
	}

	public BigInteger getIdBiometria() {
		return this.idBiometria;
	}

	public void setIdBiometria(BigInteger idBiometria) {
		this.idBiometria = idBiometria;
	}

	public Cliente getCliente() {
		return this.cliente;
	}

	public void setCliente(Cliente cliente) {
		this.cliente = cliente;
	}

	public byte[] getHuellaDigital1() {
		return this.huellaDigital1;
	}

	public void setHuellaDigital1(byte[] huellaDigital1) {
		this.huellaDigital1 = huellaDigital1;
	}

	public byte[] getHuellaDigital2() {
		return this.huellaDigital2;
	}

	public void setHuellaDigital2(byte[] huellaDigital2) {
		this.huellaDigital2 = huellaDigital2;
	}

}
