package co.edu.campusucc.sd.modelo;
// Generated 28/03/2020 03:58:47 PM by Hibernate Tools 5.4.7.Final

/**
 * FormaPago generated by hbm2java
 */
public class FormaPago implements java.io.Serializable {

	private String idFormaPago;
	private Giro giro;
	private String nombre;

	public FormaPago() {
	}

	public FormaPago(String idFormaPago, String nombre) {
		this.idFormaPago = idFormaPago;
		this.nombre = nombre;
	}

	public FormaPago(String idFormaPago, Giro giro, String nombre) {
		this.idFormaPago = idFormaPago;
		this.giro = giro;
		this.nombre = nombre;
	}

	public String getIdFormaPago() {
		return this.idFormaPago;
	}

	public void setIdFormaPago(String idFormaPago) {
		this.idFormaPago = idFormaPago;
	}

	public Giro getGiro() {
		return this.giro;
	}

	public void setGiro(Giro giro) {
		this.giro = giro;
	}

	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

}
