package co.edu.campusucc.sd.modelo;
// Generated 27/04/2020 11:48:23 AM by Hibernate Tools 5.4.7.Final

/**
 * Ubicacion generated by hbm2java
 */
public class Ubicacion implements java.io.Serializable {

	private String idUbicacion;
	private Cliente cliente;
	private String nombre;

	public Ubicacion() {
	}

	public Ubicacion(String idUbicacion, String nombre) {
		this.idUbicacion = idUbicacion;
		this.nombre = nombre;
	}

	public Ubicacion(String idUbicacion, Cliente cliente, String nombre) {
		this.idUbicacion = idUbicacion;
		this.cliente = cliente;
		this.nombre = nombre;
	}

	public String getIdUbicacion() {
		return this.idUbicacion;
	}

	public void setIdUbicacion(String idUbicacion) {
		this.idUbicacion = idUbicacion;
	}

	public Cliente getCliente() {
		return this.cliente;
	}

	public void setCliente(Cliente cliente) {
		this.cliente = cliente;
	}

	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

}
